package mclint;
import ast.ASTNode;

/**
 * A simple value object holding information about a message generated by an analysis.
 * Each analysis is responsible for creating a bunch of these, which will be passed
 * off to a report generator.
 * 
 * TODO: think about codes. Are they necessary at all? Maybe have some enums for
 * Severity, Category, etc.
 * 
 * @author ismail
 */
public class Message implements Comparable<Message> {
  private ASTNode<?> node;
  private Location location;
  private String code;
  private String description;

  public static Message regarding(ASTNode<?> node, String code, String description) {
    return new Message(node, Location.of(node), code, description);
  }

  public ASTNode<?> getAstNode() {
    return node;
  }

  public Location getLocation() {
    return location;
  }

  public String getCode() {
    return code;
  }

  public String getDescription() {
    return description;
  }

  private Message(ASTNode<?> node, Location location, String code, String description) {
    this.node = node;
    this.code = code;
    this.location = location;
    this.description = description;
  }

  @Override
  public int compareTo(Message o) {
    return getLocation().compareTo(o.getLocation());
  }

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof Message))
      return false;
    Message m = (Message) o;
    return code.equals(m.code) && description.equals(m.description) && location.equals(m.location);
  }
}
