package natlab.tame.builtin.classprop;

import java.util.ArrayList;
import beaver.*;
import natlab.tame.builtin.classprop.ast.*;
import java.util.*;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.2
 * from the grammar specification "classprop.grammar".
 */
public class ClassPropParser extends Parser {
	static public class Terminals {
		static public final short EOF = 0;
		static public final short LPAREN = 1;
		static public final short COERCE = 2;
		static public final short TYPESTRING = 3;
		static public final short NUMBER = 4;
		static public final short ID = 5;
		static public final short OROR = 6;
		static public final short QUESTION = 7;
		static public final short MULT = 8;
		static public final short RPAREN = 9;
		static public final short OR = 10;
		static public final short COMMA = 11;
		static public final short ARROW = 12;
	}

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9ojaKjB0q4GX6kowoGnPZNH#DRauCMB5o#2YA0N4GKFdXH4K10l$WR$iU#tiQtPwSssdZF" +
		"mTLVNPdkxCm1kC84fp2F3k0Zg64K3OwYXMlfq2h$qF19CeY9tnXkEYfqNDNUPHvZ314rEuD" +
		"5YvJ6Tnrd6LETBiKpQw30kO0PpM893XLrITW0tgh53x5BwpO5llJXHotZ3KKNdlxcSB5GsU" +
		"ftFSqVFBHsZo$UjSwFUBVBJ8M734z8Ddl0mhP16gFLt1sILd1flZPoP#egiatEoGIxKloPR" +
		"v5Bh7VDEPlIkVl#Bz2bJywnAziYnyVOBRRn3pKV$$4sZjpNtOf97qfTxnXz##rC#gDxbJLx" +
		"pfo$oZS6HPyrFv84YtdJ6Eueu$kiLGqAS4dIubPHlEPBmbXpQlr4rJnC=");

	private final Action[] actions;

	public ClassPropParser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			new Action() {	// [0] eqn = list.l
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final CPList l = (CPList) _symbol_l.value;
					 return l.asUnion();
				}
			},
			new Action() {	// [1] lexpr = expr.a ARROW expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final CP a = (CP) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final CP b = (CP) _symbol_b.value;
					 return new CPMap   (a, b);
				}
			},
			new Action() {	// [2] lexpr = lexpr.a OROR lexpr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final CP a = (CP) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final CP b = (CP) _symbol_b.value;
					 return new CPUnion (a, b);
				}
			},
			Action.RETURN,	// [3] lexpr = pexpr
			new Action() {	// [4] expr = expr.a QUESTION
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final CP a = (CP) _symbol_a.value;
					 return Functions.get("?",new CPList(a,null));
				}
			},
			new Action() {	// [5] expr = expr.a MULT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final CP a = (CP) _symbol_a.value;
					 return Functions.get("*",new CPList(a,null));
				}
			},
			new Action() {	// [6] expr = expr.a expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final CP a = (CP) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 2];
					final CP b = (CP) _symbol_b.value;
					 return new CPChain(a,b);
				}
			},
			new Action() {	// [7] expr = expr.a OR expr.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final CP a = (CP) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 3];
					final CP b = (CP) _symbol_b.value;
					 return new CPUnion (a, b);
				}
			},
			new Action() {	// [8] expr = NUMBER.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Number n = (Number) _symbol_n.value;
					 return new CPNum(n.intValue());
				}
			},
			new Action() {	// [9] expr = ID.s
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_s = _symbols[offset + 1];
					final String s = (String) _symbol_s.value;
					 return Functions.get(s);
				}
			},
			new Action() {	// [10] expr = LPAREN lexpr.e RPAREN
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final CP e = (CP) _symbol_e.value;
					 return e;
				}
			},
			new Action() {	// [11] expr = COERCE LPAREN lexpr.a COMMA lexpr.b RPAREN
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 3];
					final CP a = (CP) _symbol_a.value;
					final Symbol _symbol_b = _symbols[offset + 5];
					final CP b = (CP) _symbol_b.value;
					 return new CPCoerce(a,b);
				}
			},
			new Action() {	// [12] expr = TYPESTRING LPAREN list.l RPAREN
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 3];
					final CPList l = (CPList) _symbol_l.value;
					 return Functions.get("typeString",l);
				}
			},
			new Action() {	// [13] list = lexpr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final CP e = (CP) _symbol_e.value;
					 return new CPList(e,null);
				}
			},
			new Action() {	// [14] list = lexpr.a COMMA list.l
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_a = _symbols[offset + 1];
					final CP a = (CP) _symbol_a.value;
					final Symbol _symbol_l = _symbols[offset + 3];
					final CPList l = (CPList) _symbol_l.value;
					 return new CPList(a,l);
				}
			},
			Action.RETURN	// [15] pexpr = expr
		};
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
